<!--
  TabStrip — three-tab container for General / Content / Graphs with
  hide-empty-tab behavior.

  ## UTabs vs custom decision

  Nuxt UI v4's UTabs wraps Reka UI and expects `#build/ui/*` virtual module
  aliases generated by Nuxt's build pipeline. The sections/ workspace packages
  run under a standalone Vite config (no Nuxt app context) and the plugin's
  own vite.config.ts does not wire the `ui()` Nuxt UI vite plugin. Importing
  UTabs directly would produce unresolvable `#build/ui/tabs` and `#imports`
  at build time and in vitest.

  Decision: **native ARIA tablist** with Vue reactivity only. This avoids the
  Nuxt-build-pipeline dependency while meeting the full WCAG 2.1 AA tablist
  contract:
    - tablist / tab / tabpanel roles on the right elements.
    - aria-selected on the active trigger.
    - aria-controls / aria-labelledby pairing.
    - Roving tabindex within the tab list (active tab: tabindex=0; others: -1).
    - Arrow-key (Left/Right) navigation within the tab list.
    - Home / End navigation.
    - Tab key exits the tab list into the panel — standard browser behaviour
      from roving tabindex.
  No focus trap is installed — Figma's host shortcuts are not shadowed.

  When Nuxt UI v4's vite plugin is wired to the plugin's Vite config (future
  sprint), this component can be replaced with UTabs, retaining the same
  props / emits / slots contract.

  ## Props

  | Prop          | Type    | Default | Description                                   |
  | ------------- | ------- | ------- | --------------------------------------------- |
  | modelValue    | TabId   | —       | Currently active tab (v-model).               |
  | generalNull   | boolean | false   | True when the general store slice is null.    |
  | contentNull   | boolean | false   | True when the content store slice is null.    |
  | graphsNull    | boolean | false   | True when the graphs store slice is null.     |

  ## Emits

  | Event             | Payload | Description                                   |
  | ----------------- | ------- | --------------------------------------------- |
  | update:modelValue | TabId   | User selected a tab, or the active tab became |
  |                   |         | hidden and the first visible tab was promoted.|

  ## Slots

  | Slot    | Description                      |
  | ------- | -------------------------------- |
  | general | Content for the General panel.   |
  | content | Content for the Content panel.   |
  | graphs  | Content for the Graphs panel.    |

  ## Accessibility

  - role="tablist" on the list container.
  - role="tab" on each trigger, aria-selected, aria-controls.
  - role="tabpanel" on each panel, aria-labelledby, tabindex=0.
  - Roving tabindex within triggers.
  - Arrow-key + Home/End navigation within the tab list.
  - No host shortcuts shadowed (Cmd-Z, Cmd-D, Cmd-A, etc.).
  - Focus ring uses :focus-visible — removed for mouse, preserved for keyboard.
  - Color: active tab uses tokens.primary.600 text; inactive uses neutral text.
    Both exceed 4.5:1 against the panel background.
-->
<script setup lang="ts">
import { computed, watch } from 'vue';

// ---------------------------------------------------------------------------
// TabId — re-declared locally. Matches plugins/welder-editor/shared/messages.ts
// TabId. Kept local so the section has no hard dependency on the plugin package.
// ---------------------------------------------------------------------------
export type TabId = 'general' | 'content' | 'graphs';

// ---------------------------------------------------------------------------
// Internal tab descriptor
// ---------------------------------------------------------------------------
interface TabDescriptor {
  id: TabId;
  label: string;
  triggerId: string;
  panelId: string;
}

const ALL_TABS: readonly TabDescriptor[] = [
  {
    id: 'general',
    label: 'General',
    triggerId: 'tab-trigger-general',
    panelId: 'tab-panel-general',
  },
  {
    id: 'content',
    label: 'Content',
    triggerId: 'tab-trigger-content',
    panelId: 'tab-panel-content',
  },
  { id: 'graphs', label: 'Graphs', triggerId: 'tab-trigger-graphs', panelId: 'tab-panel-graphs' },
] as const;

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------
const props = withDefaults(
  defineProps<{
    /**
     * Currently active tab id (v-model).
     */
    modelValue: TabId;
    /**
     * True when the general store slice is null (no CopyWrap / Badge /
     * ImageWrap on the picked slide). Hides the General tab.
     */
    generalNull: boolean;
    /**
     * True when the content store slice is null (no CardWrap / TimelineWrap).
     * Hides the Content tab.
     */
    contentNull: boolean;
    /**
     * True when the graphs store slice is null (no TableWrap / JourneyWrap).
     * Hides the Graphs tab.
     */
    graphsNull: boolean;
  }>(),
  {
    generalNull: false,
    contentNull: false,
    graphsNull: false,
  },
);

// ---------------------------------------------------------------------------
// Emits
// ---------------------------------------------------------------------------
const emit = defineEmits<{
  /**
   * Emitted when the user selects a tab, or when the active tab becomes
   * hidden (slide change) and the first visible tab is auto-promoted.
   */
  'update:modelValue': [tab: TabId];
}>();

// ---------------------------------------------------------------------------
// Visible tabs (hide-empty rule)
// ---------------------------------------------------------------------------
const visibleTabs = computed<TabDescriptor[]>(() =>
  ALL_TABS.filter((tab) => {
    if (tab.id === 'general') return !props.generalNull;
    if (tab.id === 'content') return !props.contentNull;
    if (tab.id === 'graphs') return !props.graphsNull;
    return true;
  }),
);

// ---------------------------------------------------------------------------
// Auto-switch: when the active tab is hidden, promote to the first visible tab.
// ---------------------------------------------------------------------------
watch(
  visibleTabs,
  (tabs) => {
    const isActiveVisible = tabs.some((t) => t.id === props.modelValue);
    if (!isActiveVisible) {
      const fallback = tabs[0];
      if (fallback !== undefined) {
        emit('update:modelValue', fallback.id);
      }
    }
  },
  { immediate: true },
);

// ---------------------------------------------------------------------------
// Tab selection
// ---------------------------------------------------------------------------
function selectTab(id: TabId): void {
  if (id !== props.modelValue) {
    emit('update:modelValue', id);
  }
}

// ---------------------------------------------------------------------------
// Keyboard navigation (roving tabindex within tablist)
// ---------------------------------------------------------------------------
function handleKeydown(event: KeyboardEvent, currentId: TabId): void {
  const tabs = visibleTabs.value;
  const currentIndex = tabs.findIndex((t) => t.id === currentId);
  if (currentIndex === -1) return;

  let nextIndex: number | null = null;

  switch (event.key) {
    case 'ArrowRight':
      nextIndex = (currentIndex + 1) % tabs.length;
      break;
    case 'ArrowLeft':
      nextIndex = (currentIndex - 1 + tabs.length) % tabs.length;
      break;
    case 'Home':
      nextIndex = 0;
      break;
    case 'End':
      nextIndex = tabs.length - 1;
      break;
    default:
      return;
  }

  event.preventDefault();

  const nextTab = tabs[nextIndex];
  if (nextTab !== undefined) {
    selectTab(nextTab.id);
    // Move DOM focus to the newly active trigger.
    const el = document.getElementById(nextTab.triggerId);
    el?.focus();
  }
}
</script>

<template>
  <div class="tab-strip">
    <!--
      tablist: container for tab triggers.
      Renders nothing when all tabs are hidden — parent provides empty-state UI.
    -->
    <div
      v-if="visibleTabs.length > 0"
      role="tablist"
      aria-label="Editor tabs"
      class="tab-strip__list"
    >
      <button
        v-for="tab in visibleTabs"
        :id="tab.triggerId"
        :key="tab.id"
        role="tab"
        type="button"
        :aria-selected="tab.id === modelValue"
        :aria-controls="tab.panelId"
        :tabindex="tab.id === modelValue ? 0 : -1"
        class="tab-strip__trigger"
        :class="{ 'tab-strip__trigger--active': tab.id === modelValue }"
        @click="selectTab(tab.id)"
        @keydown="handleKeydown($event, tab.id)"
      >
        {{ tab.label }}
      </button>
    </div>

    <!--
      Tab panels. Each panel is always in the DOM but hidden via v-show so
      that slot content (form fields, editors) retains its state when the
      user switches tabs. The panel marked as hidden gets display:none via
      v-show, which removes it from the accessibility tree.
    -->
    <div
      v-for="tab in ALL_TABS"
      :id="tab.panelId"
      :key="tab.id"
      role="tabpanel"
      :aria-labelledby="tab.triggerId"
      tabindex="0"
      class="tab-strip__panel"
      :hidden="tab.id !== modelValue || !visibleTabs.some((t) => t.id === tab.id)"
    >
      <slot v-if="tab.id === 'general'" name="general" />
      <slot v-else-if="tab.id === 'content'" name="content" />
      <slot v-else-if="tab.id === 'graphs'" name="graphs" />
    </div>
  </div>
</template>

<style scoped>
/* Compact density — matches the Figma plugin iframe context. */

.tab-strip__list {
  display: flex;
  flex-direction: row;
  gap: 0;
  border-bottom: 1px solid var(--color-tab-border, #e5e7eb);
  background: var(--color-tab-bg, transparent);
}

.tab-strip__trigger {
  /* Reset */
  appearance: none;
  background: none;
  border: none;
  border-bottom: 2px solid transparent;
  cursor: pointer;
  /* Compact sizing */
  padding: 6px 12px;
  font-size: 12px;
  font-weight: 500;
  line-height: 1.5;
  color: var(--color-tab-label, #6b7280);
  /* Transition respects prefers-reduced-motion */
  transition:
    color 150ms ease,
    border-color 150ms ease;
  /* Prevent text-selection on double-click */
  user-select: none;
}

@media (prefers-reduced-motion: reduce) {
  .tab-strip__trigger {
    transition: none;
  }
}

.tab-strip__trigger:focus-visible {
  outline: 2px solid var(--color-tab-focus-ring, #2563eb);
  outline-offset: -2px;
  border-radius: 2px;
}

.tab-strip__trigger--active {
  color: var(--color-tab-active, #2563eb);
  border-bottom-color: var(--color-tab-active, #2563eb);
}

.tab-strip__trigger:hover:not(.tab-strip__trigger--active) {
  color: var(--color-tab-hover, #374151);
}

.tab-strip__panel {
  padding: 0;
  outline: none;
}

/* The `hidden` HTML attribute hides the panel from layout and a11y tree. */
.tab-strip__panel[hidden] {
  display: none;
}
</style>
