<!--
  PropertyPanel — collapsible section wrapper for Welder editor property panels.

  ## UCollapsible / Reka rejection rationale (see also docs/adr/0011-*)

  Nuxt UI v4's UCollapsible wraps Reka UI's <CollapsibleContent>. Two blockers
  apply here:

  1. Build-pipeline dependency. Nuxt UI v4 components require `#build/ui/*`
     virtual module aliases generated by Nuxt's build pipeline. Section packages
     run under standalone Vite configs (no Nuxt app context); importing
     UCollapsible directly produces unresolvable `#build/ui/collapsible` and
     `#imports` at vitest and build time. TabStrip.vue hit the same wall for
     UTabs and documented the same decision.

  2. Sync-measurement jank (T42.21 root cause). Reka UI's <CollapsibleContent>
     calls getBoundingClientRect() synchronously during open to compute the
     content height for its JS-driven height transition. Under a v-for diff
     with a Welder TableEditor (15–84 cells), this forced a browser layout in
     the same task as the diff, causing visible jank. The CSS grid-rows
     technique below avoids any JS measurement entirely.

  ## CSS grid-template-rows technique

  The body wrapper is a single-column grid container. `grid-template-rows`
  transitions between:
    `0fr`  → the inner div (min-height:0) is clipped to zero height (collapsed).
    `1fr`  → the inner div expands to its natural height (expanded).

  No JavaScript reads the content height at any point. The browser resolves
  the height during the CSS transition frame budget. This is the modern
  zero-measurement collapse pattern supported by:
    Chrome 117+, Firefox 109+, Safari 16.4+.

  `overflow:hidden` on the grid container prevents painting outside the
  collapsing boundary during the transition.

  `prefers-reduced-motion`: the CSS transition property is removed; the
  state still changes (open ↔ closed) but instantaneously.

  ## ARIA contract (ARIA APG 1.2 — Accordion pattern)

  Collapsible mode:
    - Header: <button>, implicit role="button", carries aria-expanded and
      aria-controls pointing to the body panel id.
    - Body: carries the matching id. No role="region" or role="group" — adding
      a landmark on panels this small pollutes the landmark map and is not
      required by the APG Accordion pattern.
    - Body is always in the DOM; visual collapse is CSS-only. aria-expanded on
      the button is the sole semantic signal for screen readers. This is
      consistent with the APG Accordion example that uses CSS visibility/height
      transitions rather than the `hidden` attribute (which would conflict with
      animation).
    - Chevron icon: aria-hidden="true" — decorative, never announced.

  Non-collapsible mode (collapsible=false):
    - Header: plain <div>, not interactive, not in the tab order.
    - Body: always open, no aria-expanded, no aria-controls.

  ## Props

  | Prop          | Type    | Default | Description                                         |
  | ------------- | ------- | ------- | --------------------------------------------------- |
  | title         | string  | —       | Section heading displayed in the header bar.        |
  | defaultOpen   | boolean | true    | Initial open state on mount (uncontrolled).         |
  | collapsible   | boolean | true    | When false: no toggle, no chevron, body pinned.     |

  ## Emits

  | Event        | Payload  | Description                                             |
  | ------------ | -------- | ------------------------------------------------------- |
  | update:open  | boolean  | New open state after each toggle. Enables v-model:open. |

  ## Slots

  | Slot    | Description              |
  | ------- | ------------------------ |
  | default | Body content.            |

  ## Ownership

  Owner: ui-engineer. Resolves MON-2893854185. See docs/adr/0011-*.
-->
<script setup lang="ts">
import { ref, computed, useId } from 'vue';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

const props = withDefaults(
  defineProps<{
    /**
     * Section heading displayed in the header bar.
     */
    title: string;
    /**
     * Initial open state when the component first mounts (uncontrolled
     * bootstrap). Ignored on subsequent renders — internal state owns
     * open/close after mount.
     * @default true
     */
    defaultOpen?: boolean;
    /**
     * When false: the header is a static label (not a button), the chevron
     * is hidden, and the body is permanently visible.
     * @default true
     */
    collapsible?: boolean;
  }>(),
  {
    defaultOpen: true,
    collapsible: true,
  },
);

// ---------------------------------------------------------------------------
// Emits
// ---------------------------------------------------------------------------

const emit = defineEmits<{
  /**
   * Fired after each toggle. Payload is the new open state.
   * Supports v-model:open:
   *   <PropertyPanel v-model:open="panelOpen" title="…" />
   */
  'update:open': [value: boolean];
}>();

// ---------------------------------------------------------------------------
// Internal open state
// Non-collapsible panels are always open (locked to true).
// ---------------------------------------------------------------------------

const isOpen = ref<boolean>(props.collapsible ? props.defaultOpen : true);

function toggle(): void {
  if (!props.collapsible) return;
  isOpen.value = !isOpen.value;
  emit('update:open', isOpen.value);
}

// ---------------------------------------------------------------------------
// Stable IDs for ARIA association (useId: per-component, stable across SSR)
// ---------------------------------------------------------------------------

const headerId = useId();
const bodyId = useId();

// ---------------------------------------------------------------------------
// Body CSS class — drives the CSS grid-template-rows transition
// ---------------------------------------------------------------------------

const bodyClass = computed<string>(() =>
  isOpen.value ? 'property-panel__body--open' : 'property-panel__body--closed',
);
</script>

<template>
  <section class="property-panel">
    <!--
      COLLAPSIBLE HEADER
      Rendered as <button> for native keyboard activation (Enter/Space)
      and implicit role="button". Carries aria-expanded + aria-controls.
    -->
    <button
      v-if="collapsible"
      :id="headerId"
      type="button"
      class="property-panel__header property-panel__header--button"
      :aria-expanded="isOpen"
      :aria-controls="bodyId"
      @click="toggle"
    >
      <span class="property-panel__title">{{ title }}</span>

      <!--
        Chevron: decorative, aria-hidden. Rotates 180° when open so the
        visual direction matches the open/closed state convention used in
        Figma's own property panels.
      -->
      <svg
        aria-hidden="true"
        focusable="false"
        class="property-panel__chevron"
        :class="{ 'property-panel__chevron--open': isOpen }"
        width="12"
        height="12"
        viewBox="0 0 12 12"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          d="M2.5 4.5L6 8L9.5 4.5"
          stroke="currentColor"
          stroke-width="1.5"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </svg>
    </button>

    <!--
      NON-COLLAPSIBLE HEADER
      Static <div> — not interactive, not in the tab order. No ARIA attributes
      needed (the body has no aria-controls partner in this mode).
    -->
    <div v-else :id="headerId" class="property-panel__header">
      <span class="property-panel__title">{{ title }}</span>
    </div>

    <!--
      BODY — CSS grid-template-rows collapse.

      The outer div is a single-column grid container. grid-template-rows
      transitions between 0fr (collapsed) and 1fr (expanded). No JS reads
      or writes the content height. The inner div has min-height:0, which
      is required to allow the grid track to collapse below natural height.

      The body is always in the DOM — aria-expanded on the button conveys
      the open/closed state to assistive technologies. This matches the
      ARIA APG Accordion example that uses CSS transitions rather than
      the `hidden` attribute (which would conflict with animation).

      bodyId links this element to aria-controls on the button.
    -->
    <div :id="bodyId" class="property-panel__body" :class="bodyClass">
      <div class="property-panel__body-inner">
        <slot />
      </div>
    </div>
  </section>
</template>

<style scoped>
/* ---------------------------------------------------------------------------
   Container
   --------------------------------------------------------------------------- */

.property-panel {
  display: flex;
  flex-direction: column;
  border-bottom: 1px solid var(--color-panel-border, #e5e7eb);
}

/* ---------------------------------------------------------------------------
   Header — shared base styles for both collapsible and non-collapsible modes
   --------------------------------------------------------------------------- */

.property-panel__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 6px;
  padding: 6px 10px;
  min-height: 32px;
  width: 100%;
  background: var(--color-panel-header-bg, transparent);
}

/* Button-specific reset and interactive styles */
.property-panel__header--button {
  appearance: none;
  border: none;
  cursor: pointer;
  text-align: left;
  font: inherit;
  color: inherit;
  transition: background-color 100ms ease;
}

@media (prefers-reduced-motion: reduce) {
  .property-panel__header--button {
    transition: none;
  }
}

.property-panel__header--button:hover {
  background-color: var(--color-panel-header-hover, rgba(0, 0, 0, 0.04));
}

.property-panel__header--button:focus-visible {
  outline: 2px solid var(--color-panel-focus-ring, #2563eb);
  outline-offset: -2px;
  border-radius: 2px;
}

/* ---------------------------------------------------------------------------
   Title text — compact plugin density
   --------------------------------------------------------------------------- */

.property-panel__title {
  flex: 1;
  font-size: 11px;
  font-weight: 600;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  color: var(--color-panel-title, #6b7280);
  user-select: none;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

/* ---------------------------------------------------------------------------
   Chevron icon
   --------------------------------------------------------------------------- */

.property-panel__chevron {
  flex-shrink: 0;
  color: var(--color-panel-chevron, #9ca3af);
  /* Downward chevron at 0°; rotates to upward-pointing at 180° when open. */
  transform: rotate(0deg);
  transition: transform 200ms ease;
}

@media (prefers-reduced-motion: reduce) {
  .property-panel__chevron {
    transition: none;
  }
}

.property-panel__chevron--open {
  transform: rotate(180deg);
}

/* ---------------------------------------------------------------------------
   Body — CSS grid-template-rows collapse (zero JS measurement)

   Technique:
     - Outer div: display:grid with grid-template-rows transitioning
       between 0fr (collapsed) and 1fr (expanded).
     - overflow:hidden on outer div clips content during transition.
     - Inner div: min-height:0 allows the grid track to fully compress.

   This avoids all getBoundingClientRect() / offsetHeight reads, eliminating
   the forced-layout source of T42.21 jank from Reka's <CollapsibleContent>.

   Browser support: Chrome 117+, Firefox 109+, Safari 16.4+. All three cover
   the Figma desktop app's embedded Chromium (120+) and Figma web's
   supported browser range.
   --------------------------------------------------------------------------- */

.property-panel__body {
  display: grid;
  /* Default to open (1fr); the --closed modifier overrides to 0fr. */
  grid-template-rows: 1fr;
  overflow: hidden;
  transition: grid-template-rows 200ms ease;
}

@media (prefers-reduced-motion: reduce) {
  .property-panel__body {
    transition: none;
  }
}

.property-panel__body--open {
  grid-template-rows: 1fr;
}

.property-panel__body--closed {
  grid-template-rows: 0fr;
}

.property-panel__body-inner {
  /* min-height:0 is required — without it the grid cannot compress
     below the inner div's natural height during the 0fr phase. */
  min-height: 0;
  overflow: hidden;
}
</style>
