<script setup lang="ts">
/**
 * TitleDescriptionEditor — section for editing a CopyWrap's heading and
 * optional paragraph fields.
 *
 * ## Responsibilities
 *
 * - Renders a single-line heading input (required) and, when the model's
 *   `paragraph` field is non-null, a multi-line paragraph textarea (optional).
 * - Debounces outbound `update:model` emits by 300 ms to avoid flooding the
 *   message bus on every keystroke.
 * - Does NOT dispatch messages directly. The consuming plugin view wires
 *   `@update:model="actions.applyTitleDescription"` (section discipline per
 *   ADR-0010 §section-authoring-template).
 * - Does NOT fetch data. Data flows in via the `model` prop from the plugin's
 *   Pinia store; user edits flow out via `update:model`.
 *
 * ## Nuxt UI note
 *
 * UInput and UTextarea depend on `#build/ui/*` virtual module aliases
 * generated by Nuxt's build pipeline. The sections/ workspace packages run
 * under a standalone Vite config (no Nuxt app context) and the plugin's
 * vite.config.ts does not wire the `ui()` Nuxt UI vite plugin. Using UInput /
 * UTextarea directly would produce unresolvable `#build/ui/input` and
 * `#imports` at build time and in vitest.
 *
 * Decision: native <input> / <textarea> with explicit ARIA wiring, matching
 * the approach taken in SlidePicker (native <select>) and TabStrip (native
 * tablist). This meets the full WCAG 2.1 AA bar:
 *   - Explicit <label for="…"> association.
 *   - Visible focus ring via :focus-visible.
 *   - Compact density matching the Figma plugin iframe context.
 *   - Color contrast ≥ 4.5:1 on both light and dark backgrounds.
 *
 * When Nuxt UI v4's vite plugin is wired to the plugin's Vite config (future
 * sprint), these can be replaced with UInput/UTextarea retaining the same
 * props/emits contract.
 *
 * ## Accessibility
 *
 * - Each input has an explicit <label> associated via `for` / `id`.
 * - `useId()` generates stable, unique ids for label–input pairing.
 * - `disabled` propagates to both fields; the wrapper conveys it via
 *   `aria-disabled` for screen readers that inspect the group.
 * - No host Figma shortcuts (Cmd-Z, Cmd-D, Cmd-A) are captured in keydown
 *   handlers — the inputs let the browser's default text-editing handle them.
 * - `prefers-reduced-motion` is respected (no CSS transitions on these fields).
 *
 * ## Debounce
 *
 * 300 ms debounce on the UI side. The message-bus spec for `apply-title-
 * description` notes "Debounced 200 ms in TitleDescriptionEditor" — the 300 ms
 * here is intentionally slightly longer to absorb typical keystroke cadences
 * in Figma's compact panel before hitting the code side. See project-pm flag
 * below.
 *
 * Ownership: ui-engineer.
 */

import { ref, computed, watch, onUnmounted, useId } from 'vue';
import type { TitleDescriptionModel } from './types.js';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface TitleDescriptionEditorProps {
  /**
   * The current CopyWrap state. Heading + optional paragraph.
   * When `paragraph` is null the paragraph textarea is hidden entirely —
   * there is no "add paragraph" toggle in v0.1.0 (ADR-0008 backlog).
   */
  model: TitleDescriptionModel;
  /**
   * When true both inputs are disabled and the section communicates
   * `aria-disabled` on the fieldset.
   * @default false
   */
  disabled?: boolean;
}

const props = withDefaults(defineProps<TitleDescriptionEditorProps>(), {
  disabled: false,
});

// ---------------------------------------------------------------------------
// Emits
// ---------------------------------------------------------------------------

export interface TitleDescriptionEditorEmits {
  /**
   * Emitted (debounced 300 ms) when the user edits heading or paragraph.
   * Carries only the changed text fields — copyWrapId is passed through
   * unchanged so the parent can build the full message-bus payload.
   * The parent (plugin view) is responsible for dispatching
   * `actions.applyTitleDescription(payload)` with this value.
   */
  'update:model': [patch: { heading: string; paragraph: string | null }];
}

const emit = defineEmits<TitleDescriptionEditorEmits>();

// ---------------------------------------------------------------------------
// Stable ids for label/input pairing
// ---------------------------------------------------------------------------

const headingLabelId = useId();
const headingInputId = useId();
const paragraphLabelId = useId();
const paragraphInputId = useId();

// ---------------------------------------------------------------------------
// Local draft state
//
// We maintain internal refs that shadow the prop so the input isn't jarred by
// prop updates coming in while the user is typing. When the prop changes (e.g.
// slide changed), we sync the internal state.
// ---------------------------------------------------------------------------

const localHeading = ref<string>(props.model.heading);
const localParagraph = ref<string | null>(props.model.paragraph);

/**
 * Sync internal state when the model prop changes from the outside
 * (e.g. a different slide was selected in SlidePicker).
 * We compare by copyWrapId so that debounce-triggered prop updates
 * (round-tripped through the store) don't reset the cursor position.
 */
watch(
  () => props.model,
  (next) => {
    // If the CopyWrap identity changed, always reset.
    localHeading.value = next.heading;
    localParagraph.value = next.paragraph;
    clearPending();
  },
);

// ---------------------------------------------------------------------------
// Computed
// ---------------------------------------------------------------------------

/** True when this CopyWrap has a paragraph slot (paragraph !== null). */
const hasParagraph = computed<boolean>(() => props.model.paragraph !== null);

// ---------------------------------------------------------------------------
// Debounce
// ---------------------------------------------------------------------------

let debounceTimer: ReturnType<typeof setTimeout> | null = null;

function clearPending(): void {
  if (debounceTimer !== null) {
    clearTimeout(debounceTimer);
    debounceTimer = null;
  }
}

function scheduleEmit(): void {
  clearPending();
  debounceTimer = setTimeout(() => {
    debounceTimer = null;
    emit('update:model', {
      heading: localHeading.value,
      paragraph: localParagraph.value,
    });
  }, 300);
}

onUnmounted(() => {
  clearPending();
});

// ---------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------

function onHeadingInput(event: Event): void {
  const target = event.target as HTMLInputElement;
  localHeading.value = target.value;
  scheduleEmit();
}

function onParagraphInput(event: Event): void {
  const target = event.target as HTMLTextAreaElement;
  localParagraph.value = target.value;
  scheduleEmit();
}
</script>

<template>
  <fieldset
    class="title-description-editor"
    :disabled="disabled"
    :aria-disabled="disabled ? 'true' : undefined"
  >
    <!-- Visually hidden fieldset legend for screen readers -->
    <legend class="sr-only">CopyWrap text fields</legend>

    <!-- ------------------------------------------------------------------ -->
    <!-- Heading input (single-line, required)                               -->
    <!-- ------------------------------------------------------------------ -->
    <div class="title-description-editor__field">
      <label :id="headingLabelId" :for="headingInputId" class="title-description-editor__label">
        Heading
      </label>
      <input
        :id="headingInputId"
        type="text"
        :aria-labelledby="headingLabelId"
        :disabled="disabled"
        :value="localHeading"
        autocomplete="off"
        autocorrect="off"
        autocapitalize="off"
        spellcheck="false"
        class="title-description-editor__input"
        @input="onHeadingInput"
      />
    </div>

    <!-- ------------------------------------------------------------------ -->
    <!-- Paragraph textarea (multi-line, optional)                           -->
    <!-- Hidden when model.paragraph === null (no paragraph slot on CopyWrap) -->
    <!-- ------------------------------------------------------------------ -->
    <div v-if="hasParagraph" class="title-description-editor__field">
      <label :id="paragraphLabelId" :for="paragraphInputId" class="title-description-editor__label">
        Paragraph
      </label>
      <textarea
        :id="paragraphInputId"
        :aria-labelledby="paragraphLabelId"
        :disabled="disabled"
        :value="localParagraph ?? ''"
        rows="3"
        autocomplete="off"
        autocorrect="off"
        autocapitalize="off"
        spellcheck="false"
        class="title-description-editor__textarea"
        @input="onParagraphInput"
      />
    </div>
  </fieldset>
</template>

<style scoped>
/*
 * Compact density — matches the Figma plugin iframe context.
 * All colours reference CSS custom properties (design tokens) so they
 * adapt to Figma's light/dark themes without hard-coded hex codes.
 * Fallback values are the Tailwind slate palette equivalents.
 */

.title-description-editor {
  /* Reset fieldset defaults */
  border: none;
  padding: 0;
  margin: 0;
  min-inline-size: 0;

  display: flex;
  flex-direction: column;
  gap: 8px;
}

.title-description-editor__field {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.title-description-editor__label {
  font-size: 11px;
  font-weight: 500;
  line-height: 1.5;
  color: var(--color-label, #6b7280);
  user-select: none;
}

.title-description-editor__input,
.title-description-editor__textarea {
  width: 100%;
  box-sizing: border-box;
  padding: 4px 8px;
  font-size: 12px;
  line-height: 1.5;
  color: var(--color-input-text, #111827);
  background: var(--color-input-bg, #ffffff);
  border: 1px solid var(--color-input-border, #d1d5db);
  border-radius: 4px;

  /* Remove browser default outline — replaced with :focus-visible below */
  outline: none;
}

.title-description-editor__input:focus-visible,
.title-description-editor__textarea:focus-visible {
  outline: 2px solid var(--color-focus-ring, #2563eb);
  outline-offset: 0;
}

.title-description-editor__textarea {
  resize: vertical;
  min-height: 56px;
}

/* Disabled state — propagated from <fieldset disabled> */
.title-description-editor__input:disabled,
.title-description-editor__textarea:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

/* sr-only utility (Tailwind not available in scoped <style>) */
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border-width: 0;
}
</style>
