// tests/code/golden-snapshots/table-parity.test.ts
//
// Golden-snapshot parity tests for TableWrap renderer vs v0.2.1 reference.
//
// Strategy (R10 mitigation):
//   Each test runs the current applyTableToSlot renderer against a mock-figma
//   instance that records every figma.* call as a structured op event. The
//   resulting trace is compared against a reference trace derived by running
//   the same fixture through an inline reimplementation of the v0.2.1
//   renderer logic (same algorithm, same constants as v0.2.1 source).
//
// The reference trace is NOT generated by toMatchSnapshot(). It is produced
// by a deterministic in-test function that exactly mirrors the v0.2.1 source
// (editors/table/renderer.ts as of v0.2.1). This makes drift immediately
// visible as a structured diff: which ops differ and why.
//
// Tolerance (per task spec):
//   - Variable names: OK (trace records op+structure, not symbol names)
//   - Node IDs: OK (both renderers use the same mock counter, reset between runs)
//   - Comment-only / variable-binding style changes: OK
//   NOT TOLERATED: different node hierarchy, different sizing, different text,
//   different fill/stroke structure.
//
// If a parity test fails → R10 hit. Do NOT modify renderers to fix — document
// the drift here and flag for figma-api-engineer.
//
// Owner: plugin-tester (Sprint 4 task 4.7 — MON-2894068598)

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import {
  createMockFigma,
  installMockFigma,
  uninstallMockFigma,
  makeVariable,
  type FigmaMockOp,
  type MockFigma,
} from './figma-mock';
import {
  TABLE_FIXTURE_3X3_NO_HEADER,
  TABLE_FIXTURE_10X6_WITH_HEADER,
  TABLE_FIXTURE_LARGE_TRUNCATION,
  TABLE_SLOT_HEIGHT,
} from './fixtures';
import type { TableWrapModel, TableRowModel } from '@shared/messages';

// ---------------------------------------------------------------------------
// Current renderer under test
// ---------------------------------------------------------------------------

// applyTableToSlot uses figma.* globals — the mock is installed before import
// via beforeEach so the global is present when the function runs.
// We import the module-level function after installation so TypeScript is happy.
import { applyTableToSlot, setTableVariables } from '@code/wrappers/TableWrap';

// ---------------------------------------------------------------------------
// v0.2.1 reference constants
// (from widget-src/constants.ts as of external build v0.2.1)
// ---------------------------------------------------------------------------

const V021_TABLE_WIDTHS: { sm: number; md: number; lg: number } = {
  sm: 800,
  md: 1200,
  lg: 1728,
};

// ---------------------------------------------------------------------------
// v0.2.1 reference font-size formula
// (from widget-src/editors/table/renderer.ts getFontSizes)
// ---------------------------------------------------------------------------

function v021GetFontSizes(
  slotHeight: number,
  rowCount: number,
  textSize: 'sm' | 'md' | 'lg',
): { heading: number; body: number } {
  const safeRowCount = rowCount > 0 ? rowCount : 1;
  let rowHeight = (slotHeight - 48) / safeRowCount;
  if (rowHeight < 16) rowHeight = 16;

  let mult: number;
  let headingMin: number;
  let headingMax: number;
  let bodyMin: number;
  let bodyMax: number;

  if (textSize === 'sm') {
    mult = 0.55;
    headingMin = 12;
    headingMax = 22;
    bodyMin = 10;
    bodyMax = 16;
  } else if (textSize === 'lg') {
    mult = 1.3;
    headingMin = 24;
    headingMax = 48;
    bodyMin = 20;
    bodyMax = 36;
  } else {
    mult = 1.0;
    headingMin = 16;
    headingMax = 32;
    bodyMin = 14;
    bodyMax = 24;
  }

  let heading = Math.round(rowHeight * 0.36 * mult);
  if (heading < headingMin) heading = headingMin;
  if (heading > headingMax) heading = headingMax;

  let body = Math.round(rowHeight * 0.3 * mult);
  if (body < bodyMin) body = bodyMin;
  if (body > bodyMax) body = bodyMax;

  return { heading, body };
}

// ---------------------------------------------------------------------------
// v0.2.1 reference row-padding formula
// (from widget-src/editors/table/renderer.ts computeRowPadding)
// ---------------------------------------------------------------------------

function v021ComputeRowPadding(rowCount: number): number {
  if (rowCount <= 3) return 28;
  if (rowCount <= 6) return 20;
  if (rowCount <= 9) return 14;
  return 8;
}

// ---------------------------------------------------------------------------
// v0.2.1 reference renderer reimplementation (trace-capturing)
//
// This function mirrors the v0.2.1 applyTable logic exactly, using the same
// mock-figma global. It is a faithful port of the v0.2.1 source, NOT the
// current renderer. Constants, branching, and op ordering match v0.2.1.
// ---------------------------------------------------------------------------

async function v021ApplyTable(
  slotHeight: number,
  desired: TableWrapModel,
  textVar: Variable,
  dimmerVar: Variable,
): Promise<void> {
  const f = (globalThis as unknown as Record<string, unknown>)['figma'] as {
    createFrame(): unknown;
    createText(): unknown;
    loadFontAsync(font: unknown): Promise<void>;
    variables: { setBoundVariableForPaint(paint: unknown, field: string, v: Variable): unknown };
  };

  // FIG-FONT-01: load fonts.
  await f.loadFontAsync({ family: 'Inter', style: 'Regular' });
  await f.loadFontAsync({ family: 'Inter', style: 'Medium' });
  await f.loadFontAsync({ family: 'Instrument Sans', style: 'SemiBold' });

  const slot = makeSlotProxy(slotHeight, desired.slotId);
  const textRGB = { r: 1, g: 0.957, b: 0.918 };
  const dimmerRGB = { r: 1, g: 0.698, b: 0.4 };
  const desiredWidth = V021_TABLE_WIDTHS[desired.width];

  // buildTableContainer
  const container = f.createFrame() as MockNode;
  setProp(container, 'name', 'WelderTableContent');
  setProp(container, 'layoutMode', 'VERTICAL');
  setProp(container, 'primaryAxisSizingMode', 'FIXED');
  setProp(container, 'counterAxisSizingMode', 'FIXED');
  setProp(container, 'itemSpacing', 0);
  setProp(container, 'paddingTop', 24);
  setProp(container, 'paddingBottom', 24);
  setProp(container, 'paddingLeft', 32);
  setProp(container, 'paddingRight', 32);
  setProp(container, 'cornerRadius', 55);
  setProp(container, 'clipsContent', true);
  setProp(container, 'fills', []);
  const containerStroke = f.variables.setBoundVariableForPaint(
    { type: 'SOLID', color: dimmerRGB },
    'color',
    dimmerVar,
  );
  setProp(container, 'strokes', [containerStroke]);
  setProp(container, 'strokeWeight', 2);
  setProp(container, 'strokeAlign', 'INSIDE');

  appendChild(slot, container);
  // Resize attempts (parent + slot + container)
  resizeNode(slot, desiredWidth, slotHeight);
  resizeNode(container, desiredWidth, slotHeight);
  setProp(container, 'counterAxisSizingMode', 'FIXED');
  setProp(container, 'primaryAxisSizingMode', 'FIXED');

  const hasHeader = desired.hasColumnHeader && desired.rows.length > 0;
  setProp(container, 'paddingTop', hasHeader ? 17 : 24);

  // Filter empty body rows.
  const effectiveRows: TableRowModel[] = [];
  for (let i = 0; i < desired.rows.length; i++) {
    const dRow = desired.rows[i]!;
    if (hasHeader && i === 0) {
      effectiveRows.push(dRow);
      continue;
    }
    let hasContent = false;
    for (let j = 0; j < dRow.cells.length; j++) {
      if (dRow.cells[j]!.value !== '') {
        hasContent = true;
        break;
      }
    }
    if (hasContent) effectiveRows.push(dRow);
  }

  const HEADER_HEIGHT_ESTIMATE = 50;
  const bodyRowCount = hasHeader ? effectiveRows.length - 1 : effectiveRows.length;
  const adjustedSlotHeight = hasHeader ? slotHeight - HEADER_HEIGHT_ESTIMATE : slotHeight;
  const sizes = v021GetFontSizes(
    adjustedSlotHeight,
    bodyRowCount > 0 ? bodyRowCount : 1,
    desired.textSize,
  );

  const bodyRows: MockNode[] = [];

  for (let i = 0; i < effectiveRows.length; i++) {
    const effectiveRow = effectiveRows[i]!;
    let rowFrame: MockNode;

    if (hasHeader && i === 0) {
      // buildHeaderRow
      rowFrame = f.createFrame() as MockNode;
      setProp(rowFrame, 'name', 'TableHeaderRow');
      setProp(rowFrame, 'layoutMode', 'HORIZONTAL');
      setProp(rowFrame, 'counterAxisSizingMode', 'AUTO');
      setProp(rowFrame, 'primaryAxisAlignItems', 'MIN');
      setProp(rowFrame, 'counterAxisAlignItems', 'CENTER');
      setProp(rowFrame, 'itemSpacing', 56);
      setProp(rowFrame, 'paddingTop', 0);
      setProp(rowFrame, 'paddingBottom', 0);
      setProp(rowFrame, 'paddingLeft', 32);
      setProp(rowFrame, 'paddingRight', 32);
      setProp(rowFrame, 'fills', []);
      const headerStroke = f.variables.setBoundVariableForPaint(
        { type: 'SOLID', color: dimmerRGB },
        'color',
        dimmerVar,
      );
      setProp(rowFrame, 'strokes', [headerStroke]);
      setProp(rowFrame, 'strokeAlign', 'INSIDE');
      setProp(rowFrame, 'strokeTopWeight', 0);
      setProp(rowFrame, 'strokeBottomWeight', 2);
      setProp(rowFrame, 'strokeLeftWeight', 0);
      setProp(rowFrame, 'strokeRightWeight', 0);

      // header cells
      for (let j = 0; j < effectiveRow.cells.length; j++) {
        const cell = effectiveRow.cells[j]!;
        const cellFrame = f.createFrame() as MockNode;
        setProp(cellFrame, 'name', 'TableHeaderItem-c' + String(j));
        setProp(cellFrame, 'layoutMode', 'HORIZONTAL');
        setProp(cellFrame, 'counterAxisSizingMode', 'FIXED');
        setProp(cellFrame, 'primaryAxisSizingMode', 'FIXED');
        setProp(cellFrame, 'primaryAxisAlignItems', 'MIN');
        setProp(cellFrame, 'counterAxisAlignItems', 'CENTER');
        setProp(cellFrame, 'paddingTop', 14);
        setProp(cellFrame, 'paddingBottom', 24);
        setProp(cellFrame, 'fills', []);

        const t = f.createText() as MockNode;
        setProp(t, 'fontName', { family: 'Inter', style: 'Medium' });
        setProp(t, 'fontSize', 18);
        setProp(t, 'characters', cell.value);
        setProp(t, 'textAutoResize', 'HEIGHT');
        setProp(t, 'textAlignHorizontal', 'LEFT');
        // maxLines + textTruncation (try/catch in v0.2.1 — recorded as setProperty)
        setProp(t, 'maxLines', 1);
        setProp(t, 'textTruncation', 'ENDING');
        const textFill = f.variables.setBoundVariableForPaint(
          { type: 'SOLID', color: textRGB },
          'color',
          textVar,
        );
        setProp(t, 'fills', [textFill]);

        appendChild(cellFrame, t);
        setLayoutSizing(t, 'horizontal', 'FILL');
        setLayoutSizing(t, 'vertical', 'HUG');

        appendChild(rowFrame, cellFrame);
        setLayoutSizing(cellFrame, 'horizontal', 'FILL');
        setLayoutSizing(cellFrame, 'vertical', 'FILL');
      }

      appendChild(container, rowFrame);
      setLayoutSizing(rowFrame, 'horizontal', 'FILL');
      setLayoutSizing(rowFrame, 'vertical', 'HUG');
    } else {
      const bodyIndex = hasHeader ? i - 1 : i;
      const rowPadding = v021ComputeRowPadding(bodyRowCount);

      // buildRow
      rowFrame = f.createFrame() as MockNode;
      setProp(rowFrame, 'name', 'TableRow-' + String(bodyIndex));
      setProp(rowFrame, 'layoutMode', 'HORIZONTAL');
      setProp(rowFrame, 'counterAxisSizingMode', 'AUTO');
      setProp(rowFrame, 'primaryAxisAlignItems', 'MIN');
      setProp(rowFrame, 'counterAxisAlignItems', 'CENTER');
      setProp(rowFrame, 'itemSpacing', 56);
      setProp(rowFrame, 'paddingTop', rowPadding);
      setProp(rowFrame, 'paddingBottom', rowPadding);
      setProp(rowFrame, 'paddingLeft', 32);
      setProp(rowFrame, 'paddingRight', 32);
      setProp(rowFrame, 'fills', []);

      if (bodyIndex > 0) {
        const rowStroke = f.variables.setBoundVariableForPaint(
          { type: 'SOLID', color: dimmerRGB },
          'color',
          dimmerVar,
        );
        setProp(rowFrame, 'strokes', [rowStroke]);
        setProp(rowFrame, 'strokeAlign', 'INSIDE');
        setProp(rowFrame, 'strokeTopWeight', 1);
        setProp(rowFrame, 'strokeBottomWeight', 0);
        setProp(rowFrame, 'strokeLeftWeight', 0);
        setProp(rowFrame, 'strokeRightWeight', 0);
      } else {
        setProp(rowFrame, 'strokes', []);
      }

      // buildCell for each column
      for (let j = 0; j < effectiveRow.cells.length; j++) {
        const cell = effectiveRow.cells[j]!;
        const cellFrame = f.createFrame() as MockNode;
        setProp(cellFrame, 'name', 'TableItem-c' + String(j));
        setProp(cellFrame, 'layoutMode', 'HORIZONTAL');
        setProp(cellFrame, 'counterAxisSizingMode', 'AUTO');
        setProp(cellFrame, 'primaryAxisSizingMode', 'FIXED');
        setProp(cellFrame, 'fills', []);

        const isFirst = j === 0;
        const fontName = isFirst
          ? { family: 'Instrument Sans', style: 'SemiBold' }
          : { family: 'Inter', style: 'Regular' };

        const t = f.createText() as MockNode;
        setProp(t, 'fontName', fontName);
        setProp(t, 'fontSize', isFirst ? sizes.heading : sizes.body);
        setProp(t, 'characters', cell.value);
        setProp(t, 'textAutoResize', 'HEIGHT');
        setProp(t, 'textAlignHorizontal', 'LEFT');
        const textFill = f.variables.setBoundVariableForPaint(
          { type: 'SOLID', color: textRGB },
          'color',
          textVar,
        );
        setProp(t, 'fills', [textFill]);

        appendChild(cellFrame, t);
        setLayoutSizing(t, 'horizontal', 'FILL');
        setLayoutSizing(t, 'vertical', 'HUG');

        appendChild(rowFrame, cellFrame);
        setLayoutSizing(cellFrame, 'horizontal', 'FILL');
        setLayoutSizing(cellFrame, 'vertical', 'HUG');
      }

      appendChild(container, rowFrame);
      setLayoutSizing(rowFrame, 'horizontal', 'FILL');
      setLayoutSizing(rowFrame, 'vertical', 'FILL');

      bodyRows.push(rowFrame);
    }
  }

  // applyBodyTruncation
  for (let r = 0; r < bodyRows.length; r++) {
    const row = bodyRows[r]!;
    const rowChildren = getChildren(row);
    for (let c = 0; c < rowChildren.length; c++) {
      const cell = rowChildren[c]!;
      if (getNodeType(cell) !== 'FRAME') continue;
      // cell FIXED + FILL
      setProp(cell, 'counterAxisSizingMode', 'FIXED');
      setLayoutSizing(cell, 'vertical', 'FILL');

      // find text node
      const textNode = findOneText(cell);
      if (!textNode) continue;
      setProp(textNode, 'textAutoResize', 'NONE');
      setLayoutSizing(textNode, 'horizontal', 'FILL');
      setLayoutSizing(textNode, 'vertical', 'FILL');
      setProp(textNode, 'textTruncation', 'ENDING');
    }
  }

  // Write pluginData on slot
  setPluginData(slot, 'width', desired.width);
  setPluginData(slot, 'hasColumnHeader', desired.hasColumnHeader ? '1' : '0');
  setPluginData(slot, 'textSize', desired.textSize);
  setPluginData(slot, 'kind', 'welder-tablewrap');
  setPluginData(slot, 'v', '3');
}

// ---------------------------------------------------------------------------
// Helpers for v0.2.1 reference renderer (operate on the mock's proxy nodes)
// ---------------------------------------------------------------------------

type MockNode = Record<string, unknown>;

function makeSlotProxy(slotHeight: number, slotId: string): MockNode {
  // Minimal slot stub — operations on it get recorded through the mock.
  // We use the mock's createFrame and then override id/height.
  const f = (globalThis as unknown as Record<string, unknown>)['figma'] as {
    createFrame(): unknown;
  };
  const slot = f.createFrame() as MockNode;
  // Override the auto-id with the stable slotId and set height.
  // We reach into the proxy's handler by setting via standard assignment.
  // The mock's proxy will record these as setProperty ops.
  slot['name'] = 'SlotProxy-' + slotId;
  // Height is read by the renderer (slot.height); set it on the underlying object.
  // The proxy returns props.height from its get handler.
  // Since our proxy doesn't track 'height' in directProps, we need a workaround.
  // The proxy stores height in props, but we can't directly access props from outside.
  // Instead, we call resize on the slot proxy to set its height.
  (slot as unknown as { resize(w: number, h: number): void }).resize(800, slotHeight);
  return slot;
}

function setProp(node: MockNode, key: string, value: unknown): void {
  node[key] = value;
}

function appendChild(parent: MockNode, child: MockNode): void {
  (parent as unknown as { appendChild(c: unknown): void }).appendChild(child);
}

function resizeNode(node: MockNode, w: number, h: number): void {
  (node as unknown as { resize(w: number, h: number): void }).resize(w, h);
}

function setLayoutSizing(node: MockNode, axis: 'horizontal' | 'vertical', value: string): void {
  if (axis === 'horizontal') {
    node['layoutSizingHorizontal'] = value;
  } else {
    node['layoutSizingVertical'] = value;
  }
}

function setPluginData(node: MockNode, key: string, value: string): void {
  (node as unknown as { setPluginData(k: string, v: string): void }).setPluginData(key, value);
}

function getChildren(node: MockNode): MockNode[] {
  return (node['children'] as MockNode[] | undefined) ?? [];
}

function getNodeType(node: MockNode): string {
  return node['type'] as string;
}

function findOneText(cell: MockNode): MockNode | null {
  const children = getChildren(cell);
  for (const child of children) {
    if (getNodeType(child) === 'TEXT') return child;
    // Not recursive — cells only have one level of children in our mock.
  }
  return null;
}

// ---------------------------------------------------------------------------
// Slot stub for current renderer (applyTableToSlot takes a FrameNode)
// ---------------------------------------------------------------------------

function makeCurrentSlot(slotHeight: number, slotId: string): unknown {
  const f = (globalThis as unknown as Record<string, unknown>)['figma'] as {
    createFrame(): unknown;
  };
  const slot = f.createFrame() as MockNode;
  slot['name'] = 'CurrentSlot-' + slotId;
  (slot as unknown as { resize(w: number, h: number): void }).resize(800, slotHeight);
  return slot;
}

// ---------------------------------------------------------------------------
// Normalize traces for comparison
//
// Some ops are inherently non-comparable between v0.2.1 and current because
// the current renderer wraps everything in withAtomic() (ADR-0004), which
// adds figma.commitUndo-equivalent semantics. The op log itself doesn't
// include the atomic wrapper — ops are the same. We strip 'createFrame' ops
// for the slot proxy itself (slot is not created by the renderer in production)
// and normalize fills/strokes to structural equality (not identity).
// ---------------------------------------------------------------------------

function stripSlotCreationOps(log: FigmaMockOp[]): FigmaMockOp[] {
  // The first createFrame op in any trace is the slot proxy we created in the
  // test setup (makeSlotProxy / makeCurrentSlot). The renderer doesn't create
  // the slot — it receives it. We strip the first createFrame + its resize
  // so only renderer-generated ops remain.
  let slotFrameId: string | null = null;
  const result: FigmaMockOp[] = [];
  let skipped = false;
  for (const op of log) {
    if (!skipped && op.op === 'createFrame') {
      slotFrameId = op.id;
      skipped = true;
      continue; // skip slot's createFrame
    }
    // Skip the slot's resize (first resize after createFrame, before anything renderer does)
    if (slotFrameId && op.op === 'resize' && op.nodeId === slotFrameId) {
      slotFrameId = null; // only skip the first resize on the slot
      continue;
    }
    // Skip setProperty ops on the slot frame node (the name we set)
    if (slotFrameId && op.op === 'setProperty' && op.nodeId === slotFrameId) {
      continue;
    }
    result.push(op);
  }
  return result;
}

// Normalize IDs: remap node IDs to sequential integers in encounter order.
// This removes the absolute ID values (which depend on prior test execution)
// so traces from two independent runs with the same mock-reset are comparable.
function normalizeIds(log: FigmaMockOp[]): Array<{ op: string; [key: string]: unknown }> {
  const idMap = new Map<string, number>();
  let counter = 0;

  function normId(id: string | null): string | null {
    if (id === null) return null;
    if (!idMap.has(id)) {
      idMap.set(id, ++counter);
    }
    return `N${idMap.get(id)!}`;
  }

  return log.map((op) => {
    switch (op.op) {
      case 'createFrame':
      case 'createText':
      case 'createRectangle':
      case 'createInstance':
        return { ...op, id: normId(op.id) };
      case 'appendChild':
        return { ...op, parentId: normId(op.parentId), childId: normId(op.childId) };
      case 'setProperty':
      case 'setPluginData':
      case 'resize':
      case 'setPosition':
      case 'layoutSizing':
      case 'remove':
        return { ...op, nodeId: normId(op.nodeId) };
      case 'findOne':
        return { ...op, nodeId: normId(op.nodeId), result: normId(op.result) };
      case 'setBoundVariable':
        return { ...op, nodeId: normId(op.nodeId) };
      default:
        return op;
    }
  });
}

function captureAndNormalize(log: FigmaMockOp[]): Array<{ op: string; [key: string]: unknown }> {
  return normalizeIds(stripSlotCreationOps(log));
}

// ---------------------------------------------------------------------------
// Test variables (shared across fixtures)
// ---------------------------------------------------------------------------

const TEXT_VAR = makeVariable('Text');
const DIMMER_VAR = makeVariable('TextDimmer');

// ---------------------------------------------------------------------------
// Test suite
// ---------------------------------------------------------------------------

describe('TableWrap golden-snapshot parity (R10)', () => {
  let mock: MockFigma;

  beforeEach(() => {
    mock = createMockFigma();
    installMockFigma(mock);
    setTableVariables(TEXT_VAR, DIMMER_VAR);
  });

  afterEach(() => {
    mock.resetLog();
    uninstallMockFigma();
    setTableVariables(null, null);
  });

  // ─── TABLE-F1: 3×3, no header, md width ─────────────────────────────────

  it('TABLE-F1: 3×3 no-header trace matches v0.2.1 reference', async () => {
    const fixture = TABLE_FIXTURE_3X3_NO_HEADER;

    // --- v0.2.1 reference trace ---
    mock.resetLog();
    await v021ApplyTable(TABLE_SLOT_HEIGHT, fixture, TEXT_VAR, DIMMER_VAR);
    const referenceTrace = captureAndNormalize(mock.log);

    // --- current renderer trace ---
    mock.resetLog();
    const slot = makeCurrentSlot(TABLE_SLOT_HEIGHT, fixture.slotId) as FrameNode;
    await applyTableToSlot(slot, fixture);
    const currentTrace = captureAndNormalize(mock.log);

    // If this assertion fails, log the diff details before throwing.
    if (!deepEqual(currentTrace, referenceTrace)) {
      const diffs = findTraceDiffs(referenceTrace, currentTrace);
      console.error('\n[PARITY FAIL] TABLE-F1 drift detected:');
      console.error('  Reference ops:', referenceTrace.length);
      console.error('  Current ops:  ', currentTrace.length);
      diffs.forEach((d) => console.error(' ', d));
    }

    expect(currentTrace).toEqual(referenceTrace);
  });

  // ─── TABLE-F2: 10×6, with header, md width ───────────────────────────────

  it('TABLE-F2: 10×6 with-header trace matches v0.2.1 reference', async () => {
    const fixture = TABLE_FIXTURE_10X6_WITH_HEADER;

    mock.resetLog();
    await v021ApplyTable(TABLE_SLOT_HEIGHT, fixture, TEXT_VAR, DIMMER_VAR);
    const referenceTrace = captureAndNormalize(mock.log);

    mock.resetLog();
    const slot = makeCurrentSlot(TABLE_SLOT_HEIGHT, fixture.slotId) as FrameNode;
    await applyTableToSlot(slot, fixture);
    const currentTrace = captureAndNormalize(mock.log);

    if (!deepEqual(currentTrace, referenceTrace)) {
      const diffs = findTraceDiffs(referenceTrace, currentTrace);
      console.error('\n[PARITY FAIL] TABLE-F2 drift detected:');
      console.error('  Reference ops:', referenceTrace.length);
      console.error('  Current ops:  ', currentTrace.length);
      diffs.forEach((d) => console.error(' ', d));
    }

    expect(currentTrace).toEqual(referenceTrace);
  });

  // ─── TABLE-F3: large (header + 11 body rows), lg width, sm textSize ──────

  it('TABLE-F3: large truncation trace matches v0.2.1 reference', async () => {
    const fixture = TABLE_FIXTURE_LARGE_TRUNCATION;

    mock.resetLog();
    await v021ApplyTable(TABLE_SLOT_HEIGHT, fixture, TEXT_VAR, DIMMER_VAR);
    const referenceTrace = captureAndNormalize(mock.log);

    mock.resetLog();
    const slot = makeCurrentSlot(TABLE_SLOT_HEIGHT, fixture.slotId) as FrameNode;
    await applyTableToSlot(slot, fixture);
    const currentTrace = captureAndNormalize(mock.log);

    if (!deepEqual(currentTrace, referenceTrace)) {
      const diffs = findTraceDiffs(referenceTrace, currentTrace);
      console.error('\n[PARITY FAIL] TABLE-F3 drift detected:');
      console.error('  Reference ops:', referenceTrace.length);
      console.error('  Current ops:  ', currentTrace.length);
      diffs.forEach((d) => console.error(' ', d));
    }

    expect(currentTrace).toEqual(referenceTrace);
  });
});

// ---------------------------------------------------------------------------
// Diff utilities (fail-path diagnostics)
// ---------------------------------------------------------------------------

function deepEqual(a: unknown, b: unknown): boolean {
  return JSON.stringify(a) === JSON.stringify(b);
}

function findTraceDiffs(
  reference: Array<{ op: string; [key: string]: unknown }>,
  current: Array<{ op: string; [key: string]: unknown }>,
): string[] {
  const diffs: string[] = [];
  const len = Math.max(reference.length, current.length);
  for (let i = 0; i < len; i++) {
    const r = reference[i];
    const c = current[i];
    if (r === undefined) {
      diffs.push(`[+${i}] current has extra op: ${JSON.stringify(c)}`);
    } else if (c === undefined) {
      diffs.push(`[-${i}] reference has op not in current: ${JSON.stringify(r)}`);
    } else if (JSON.stringify(r) !== JSON.stringify(c)) {
      diffs.push(`[~${i}] diff:`);
      diffs.push(`  ref: ${JSON.stringify(r)}`);
      diffs.push(`  cur: ${JSON.stringify(c)}`);
    }
    if (diffs.length > 30) {
      diffs.push('... (truncated at 30 diffs)');
      break;
    }
  }
  return diffs;
}
