<script setup lang="ts">
/**
 * BadgeEditor — section for editing a Badge label (text) and icon (Lucide key).
 *
 * ## Slot contract
 *
 * The icon picker is decoupled from this section via a named slot:
 *
 *   <slot name="icon-picker" v-bind="{ icon, onChange: setIcon }" />
 *
 * The consumer wires whatever icon picker component is available (task 2.6
 * IconPicker, or a placeholder during development). BadgeEditor does not
 * import or reference any specific icon picker.
 *
 * ## UInput vs plain <input> decision
 *
 * Nuxt UI v4's UInput relies on virtual module aliases (`#build/ui/*`,
 * `#imports`) generated by Nuxt's build pipeline. The sections/ workspace
 * packages run under a standalone Vite config (no Nuxt app context); those
 * aliases are not wired. Importing UInput here would produce unresolvable
 * module errors in vitest and at build time.
 *
 * Decision: plain <input> with explicit <label> association, matching Nuxt
 * UI's WCAG 2.1 AA contract for text inputs:
 *   - Explicit <label> linked via htmlFor / id pair.
 *   - Visible focus ring via :focus-visible.
 *   - Disabled state propagated to the input element.
 *   - aria-label on icon-picker wrapper describes the region.
 *
 * When the plugin's Vite config is wired with the Nuxt UI vite plugin
 * (future sprint), UInput can be adopted here with no contract change.
 *
 * ## Emit timing
 *
 * update:model is debounced 300 ms after the last label keystroke or icon
 * change so the parent (and the message bus) is not flooded during fast
 * typing. The debounce is reset on each new edit.
 *
 * ## Data flow
 *
 * Props flow in (model + disabled). User edits flow out via emits.
 * This section does NOT dispatch messages to the Figma code side — that is
 * the consuming plugin view's responsibility (per ADR-0010 §section contract).
 *
 * ## Accessibility
 *
 * - Label input: visible <label> associated via for/id. Screen readers
 *   announce "Badge label" on focus.
 * - Icon picker slot wrapper: aria-label="Badge icon" groups the slot
 *   content for AT users; the concrete picker inside the slot must supply
 *   its own internal focus management and labeling.
 * - Disabled state: input[disabled] removes it from the tab order and is
 *   conveyed to AT. The slot receives `disabled` so the consumer can pass
 *   it to the icon picker.
 * - No live region needed: updates are user-initiated and synchronous from
 *   the user's perspective (the debounce is transparent).
 *
 * Ownership: ui-engineer.
 * Resolves: MON-2893850050 (Sprint 2, Task 2.5).
 */

import { ref, watch, onBeforeUnmount, useId } from 'vue';
import type { BadgeModel } from './types.js';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface BadgeEditorProps {
  /**
   * The current badge state. Drives both the label input and the icon slot.
   * Pass the BadgeSection slice from the slide store.
   */
  model: BadgeModel;
  /**
   * When true, the label input is disabled and the slot receives
   * disabled=true so the consumer can disable the icon picker as well.
   */
  disabled?: boolean;
}

const props = withDefaults(defineProps<BadgeEditorProps>(), {
  disabled: false,
});

// ---------------------------------------------------------------------------
// Emits
// ---------------------------------------------------------------------------

export interface BadgeEditorEmits {
  /**
   * Fired (debounced 300 ms) when label or icon changes.
   * The payload carries the full updated model — consumers replace the
   * whole model slice and dispatch apply-badge to the code side.
   */
  'update:model': [model: Pick<BadgeModel, 'label' | 'icon'>];
}

const emit = defineEmits<BadgeEditorEmits>();

// ---------------------------------------------------------------------------
// Stable IDs for aria association
// ---------------------------------------------------------------------------

const labelInputId = useId();
const iconGroupLabelId = useId();

// ---------------------------------------------------------------------------
// Internal reactive state — mirrors prop, updated on prop change
// ---------------------------------------------------------------------------

/** Local copy of label, kept in sync with props.model.label. */
const label = ref<string>(props.model.label);
/** Local copy of icon key, kept in sync with props.model.icon. */
const icon = ref<string>(props.model.icon);

/**
 * Keep local state in sync when the parent replaces the model entirely
 * (e.g. slide selection change). Avoid triggering the debounce for prop
 * sync updates by only updating when values actually differ.
 */
watch(
  () => props.model,
  (next) => {
    if (next.label !== label.value) label.value = next.label;
    if (next.icon !== icon.value) icon.value = next.icon;
  },
  { deep: false },
);

// ---------------------------------------------------------------------------
// Debounced emit
// ---------------------------------------------------------------------------

let debounceTimer: ReturnType<typeof setTimeout> | null = null;

function scheduleEmit(): void {
  if (debounceTimer !== null) clearTimeout(debounceTimer);
  debounceTimer = setTimeout(() => {
    debounceTimer = null;
    emit('update:model', { label: label.value, icon: icon.value });
  }, 300);
}

onBeforeUnmount(() => {
  if (debounceTimer !== null) {
    clearTimeout(debounceTimer);
    debounceTimer = null;
  }
});

// ---------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------

function handleLabelInput(event: Event): void {
  const target = event.target as HTMLInputElement;
  label.value = target.value;
  scheduleEmit();
}

/**
 * Called by the icon-picker slot via the `onChange` binding.
 * Accepts the new Lucide icon key.
 */
function setIcon(newIcon: string): void {
  if (newIcon === icon.value) return;
  icon.value = newIcon;
  scheduleEmit();
}
</script>

<template>
  <div class="badge-editor">
    <!-- Label field -->
    <div class="badge-editor__field">
      <label :for="labelInputId" class="badge-editor__label"> Badge label </label>
      <input
        :id="labelInputId"
        type="text"
        :value="label"
        :disabled="disabled"
        class="badge-editor__input"
        autocomplete="off"
        spellcheck="false"
        @input="handleLabelInput"
      />
    </div>

    <!-- Icon picker slot -->
    <!--
      role="group" + aria-labelledby is valid ARIA (the group role accepts
      aria-labelledby). This groups the slot content under the "Badge icon"
      label for AT users without relying on aria-label on a generic div
      (which would be an aria-prohibited-attr violation per WCAG 2.1 AA).
    -->
    <div role="group" :aria-labelledby="iconGroupLabelId" class="badge-editor__field">
      <span :id="iconGroupLabelId" class="badge-editor__label">Badge icon</span>
      <!--
        Slot contract:
          icon     — current Lucide key string (read-only for the picker).
          onChange — callback the picker calls with the new Lucide key.
          disabled — boolean forwarded from the section's disabled prop.

        Example consumer wiring (once IconPicker lands in task 2.6):
          <template #icon-picker="{ icon, onChange, disabled }">
            <IconPicker :value="icon" :disabled="disabled" @select="onChange" />
          </template>
      -->
      <slot name="icon-picker" :icon="icon" :on-change="setIcon" :disabled="disabled" />
    </div>
  </div>
</template>

<style scoped>
.badge-editor {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.badge-editor__field {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.badge-editor__label {
  font-size: 11px;
  font-weight: 500;
  line-height: 1.4;
  color: var(--color-label, #6b7280);
  user-select: none;
}

.badge-editor__input {
  width: 100%;
  padding: 4px 8px;
  font-size: 12px;
  line-height: 1.5;
  color: var(--color-input-text, #111827);
  background: var(--color-input-bg, #ffffff);
  border: 1px solid var(--color-input-border, #d1d5db);
  border-radius: 4px;
  outline: none;
  /* Prevent autocomplete styling overrides */
  appearance: none;
  /* Smooth focus transition — suppressed by prefers-reduced-motion */
  transition: border-color 100ms ease;
  box-sizing: border-box;
}

@media (prefers-reduced-motion: reduce) {
  .badge-editor__input {
    transition: none;
  }
}

.badge-editor__input:focus-visible {
  border-color: var(--color-input-focus, #2563eb);
  box-shadow: 0 0 0 2px var(--color-input-focus-ring, rgba(37, 99, 235, 0.2));
}

.badge-editor__input:disabled {
  color: var(--color-input-disabled-text, #9ca3af);
  background: var(--color-input-disabled-bg, #f9fafb);
  border-color: var(--color-input-disabled-border, #e5e7eb);
  cursor: not-allowed;
}
</style>
